In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

ModuleNotFoundError: No module named 'seaborn'

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
A1 = np.arange(1,21)
f1 = lambda x: 2**x/x
A1 = f1(A1)
A1

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
f2  = lambda x: 0.1**(3*x)*0.2**(4*x)
A2 = np.arange(0,6)
A2 = f2(A2)
A2 = np.sum(A2)
A2

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
A3 = np.zeros((8,8))
A3[1::2,::2] = 1
A3[::2,1::2] = 1
A3

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))

PFI = np.zeros((5,2))
PFI[:,0] = np.hypot(X[:,0],X[:,1])
PFI[:,1] = np.arctan(X[:,1]/X[:,0])
PFI

array([[0.85142432, 0.51015331],
       [0.51273485, 1.34541467],
       [1.0111779 , 0.55155308],
       [0.82696339, 1.50902212],
       [0.48568255, 0.94594998]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))

MAX5 = np.argmax(X)
MAX5

56

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [8]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

VSPXXX61 = X[:,0] - y[0,0]
VSPXXX62 = X[:,1] - y[0,1]
DIST6 = np.hypot(VSPXXX61,VSPXXX62)
min6 = np.argmin(DIST6)
X[min6]

array([0.84418547, 0.56496463])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [9]:
def f7(x):
    if x < 0:
        return x*x + 2*x + 6
    elif x <= 2:
        return x + 6
    else:
        return x*x + 4*x - 4
X7 = np.linspace(-3,3,100)
fvec7 = np.vectorize(f7)
Y7 = fvec7(X7)
Y7

array([ 9.        ,  8.76124885,  8.52984389,  8.30578512,  8.08907254,
        7.87970615,  7.67768595,  7.48301194,  7.29568411,  7.11570248,
        6.94306703,  6.77777778,  6.61983471,  6.46923783,  6.32598714,
        6.19008264,  6.06152433,  5.94031221,  5.82644628,  5.71992654,
        5.62075298,  5.52892562,  5.44444444,  5.36730946,  5.29752066,
        5.23507805,  5.17998163,  5.1322314 ,  5.09182736,  5.05876951,
        5.03305785,  5.01469238,  5.00367309,  5.        ,  5.00367309,
        5.01469238,  5.03305785,  5.05876951,  5.09182736,  5.1322314 ,
        5.17998163,  5.23507805,  5.29752066,  5.36730946,  5.44444444,
        5.52892562,  5.62075298,  5.71992654,  5.82644628,  5.94031221,
        6.03030303,  6.09090909,  6.15151515,  6.21212121,  6.27272727,
        6.33333333,  6.39393939,  6.45454545,  6.51515152,  6.57575758,
        6.63636364,  6.6969697 ,  6.75757576,  6.81818182,  6.87878788,
        6.93939394,  7.        ,  7.06060606,  7.12121212,  7.18

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [10]:
X = np.random.random((10, 10))

VSP8 = np.mean(X, axis = 1, keepdims=True)
A8 = X - VSP8
print(np.mean(A8, axis = 1))

[ 2.22044605e-17  4.44089210e-17 -3.33066907e-17  6.66133815e-17
 -5.55111512e-17  3.33066907e-17  2.22044605e-17 -1.22124533e-16
 -6.66133815e-17 -5.55111512e-17]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [11]:
X = np.random.normal(loc=5, scale=2., size=1000)
print(np.mean(X), np.var(X))

5.059963603155686 3.7263773206374697


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [57]:
n = 5
r = np.arange(0,n)
X10 = np.tile(r, (n,1))
rows, column_indices = np.ogrid[:n, :n]
r *= -1
r[r < 0] += n
column_indices = column_indices - r[:,np.newaxis]
result = X10[rows, column_indices]
print(result)

[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [13]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for i in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
        res.append(idx)
    return res

            
print(sample([50, 3, 1, 7, 20], 5))

[0, 0, 4, 0, 3]


Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [15]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)

    def f11(ranf):
        val = s * ranf
        cusum = np.cumsum(x)
        idx = np.searchsorted(cusum, val)
        return idx

    agr = np.random.random(c)
    g = f11(agr)
    return list(g)

            
print(sample([50, 3, 1, 7, 20], 5))

[0, 3, 0, 0, 0]
